name: 'climate_data'
version: '1.0.0'
config-version: 2

profile: 'climate_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  climate_data:
    materialized: table
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table 